// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf6OtASUbCI1LNhSXXeAWrzshhhxxBNRQ',
    appId: '1:1033185347348:web:435e3f15d4613e361fe401',
    messagingSenderId: '1033185347348',
    projectId: 'job-timer-81ccb',
    authDomain: 'job-timer-81ccb.firebaseapp.com',
    storageBucket: 'job-timer-81ccb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9cFDz9IB-TrIBd9YNnBM3iPYgqsH05Fg',
    appId: '1:1033185347348:android:a58080fbc92edf311fe401',
    messagingSenderId: '1033185347348',
    projectId: 'job-timer-81ccb',
    storageBucket: 'job-timer-81ccb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVWed-iJ5XetbWNw7kqroWkZEWYYM7UIs',
    appId: '1:1033185347348:ios:5395c83a81c53d411fe401',
    messagingSenderId: '1033185347348',
    projectId: 'job-timer-81ccb',
    storageBucket: 'job-timer-81ccb.appspot.com',
    iosClientId: '1033185347348-95oif23ulii4i5sgo4nt4mm34pburt06.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobTimer',
  );
}
